const express = require("express")
const registerUser = require("../controllers/auth/register")
const loginUser = require("../controllers/auth/login")
const logoutUser = require("../controllers/auth/logout")
const resetPassword = require("../controllers/auth/resetPassword")
const verifyOtp = require("../controllers/auth/verifyOtp")
const router = express.Router()
const geoIpMiddleware = require("../middleware/geoIpMiddleware")
const refreshTokenRotation = require("../controllers/auth/token")
const authMiddleware = require("../middleware/authMiddleware")
const {passwordLimiter,otpLimiter} = require("../utils/rateLimiter")


router.post("/register",geoIpMiddleware,registerUser)
router.post("/login",passwordLimiter,geoIpMiddleware,loginUser)
router.post("/logout",logoutUser)
router.post("/verify-otp",otpLimiter,verifyOtp)
router.post("/reset-password",resetPassword)
router.post("/refresh-token",geoIpMiddleware,authMiddleware,refreshTokenRotation)
module.exports = router
